name: Feature request
description: Propose new functionality
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user / team need are we serving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - api
        - core
        - sports
        - workbench
        - dagster
        - infra
        - docs
    validations:
      required: true
